### PR TITLE
Reorder table in alphabetically order to make it easier to read

### PR DESCRIPTION
**Pull request by BKSpurgeon**
* Easier to scan and check a client.

A small change, but i hope it is useful.

### CODE REVIEW

**Comment by paul** [comment]
It was sorted by `Time` before, which was probably the original intent, and IMO more useful. 🤷

**Comment by tarcieri** [comment]
The table is also ancient and should probably be removed or recreated from scratch

**Comment by tarcieri** [comment]
The best way you could possibly improve the content of this section is by performing a new benchmark 😉

**Comment by BKSpurgeon** [comment]
@tarcieri Tony, I appreciate the comment. I wonder about the usefulness of these performance tests -- they tend to be opinionated. I can't guarantee anything, but I can make an attempt. Please don't hold me to it.

**Pull request closed without merging**
