### PR TITLE
Remove all deprecations (closes #208)

### LINKED ISSUE #208: Remove all deprecations

### PR DESCRIPTION
**Pull request by tarcieri**
I'd still like to go forward with a 1.0 release (and at least blog about it)

This removes all deprecations and documents replacements where applicable.

### CODE REVIEW

**Comment by tarcieri** [comment]
Ugh, no `Hash()` in Ruby 1.9.3 :cry:

**Comment by zanker** [comment]
What are we waiting on to deprecate 1.9.3 again, something with the Twitter gem?

**Comment by tarcieri** [comment]
@zanker I think @sferik would prefer we don't deprecate 1.9.3 without a good reason. #242 is still open FWIW

**Comment by tarcieri** [comment]
Build is green now.

I'll push a `0-9-stable` branch before merging this. Anyone have any thoughts on it otherwise?

**Comment by zanker** [comment]
LGTMs

**Comment by ixti** [comment]
:+1:

**Comment by tarcieri** [comment]
:shipit:

**Pull request merged**
