### PR TITLE
Fix the pinning of Rubocop version

### PR DESCRIPTION
**Pull request by drwl**
This PR pins Rubocop to the last version that's supported by Ruby 2.5. I think it was improperly pinned/Rubocop's versioning went different than expected.

- The lint step was running Ruby 2.5 and as a result was using Rubocop 1.28.2.
- In the gemfile, `gem "rubocop", "~> 1.21"` allows for any versions < 2. 
- As a result, there's most likely drift between people's Rubocop version and the one used in the lint step.
- Rubocop 1.29.0 is the first version that sets the requirement for Ruby 2.6+.

Some PRs are experiencing unrelated linting issues. I don't have the context to safely make these changes, but this change should unblock folks.

### CODE REVIEW

**Comment by drwl** [comment]
It's not clear why the lint step is failing:

https://github.com/httprb/http/runs/6890611978?check_suite_focus=true
```
Run bundle exec rubocop --format progress --color
Your RubyGems version (2.7.6.3) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
Error: unrecognized cop or department Gemspec/DeprecatedAttributeAssignment found in .rubocop_todo.yml
Did you mean `Gemspec/OrderedDependencies`?
Error: Process completed with exit code 2.
```

Locally this passes for me
```
➜  httprb-gem git:(drwl/fix-rubocop-issues) ✗ bundle exec rubocop --format progress --color
Inspecting 80 files
................................................................................

80 files inspected, no offenses detected
```

**Comment by drwl** [comment]
@tarcieri I'm not able to request reviewers, but this should fix the failed linting step in various PRs.

**Comment by drwl** [comment]
cc @ixti

**Comment by tarcieri** [comment]
Thanks!

**Pull request merged**
