### PR TITLE
Remove .ruby-version file

### PR DESCRIPTION
**Pull request by janko-m**
The HTTP.rb codebase runs just as well on other Ruby versions, it's not necessary to use 2.4.0 specifically. This is inconvenient when using rbenv, because rbenv will automatically try to switch to the version specified in .ruby-version, and complain if you don't have it installed.

### CODE REVIEW

**Comment by ixti** [comment]
Can you please add it to `.gitignore` then?

**Comment by janko-m** [comment]
@ixti I can add it to my global `.gitignore`, but it won't change anything because it's still checked into the version control here. If I delete it locally the git status will still be left "dirty", because its deletion is tracked.

**Comment by janko-m** [comment]
Oh, I see that you might have meant this `.gitignore`, I'll add it.

**Comment by ixti** [comment]
Thanks! RuboCop also uses .ruby-version if no trarget specified in config. :D
Please fix .rubocop.yml as well by adding `TargetRubyVersion: 2.4` under `AllCops` section.

**Comment by janko-m** [comment]
@ixti It seems that GitHub isn't updating the PR with the new changes I'm pushing 🤔

**Comment by ixti** [comment]
Thanks! Merged in!

**Pull request merged**
