### PR TITLE
Add pronunciation for httprb.

### PR DESCRIPTION
**Pull request by jkingdon**
Not that I have a problem with "The Gem!" although that just raises the
question of how to pronounce the exclamation point.

### CODE REVIEW

**Comment by tarcieri** [comment]
lol whut

**Comment by jkingdon** [comment]
LOL is the correct response. Whether you want to merge this depends on your sense of humor as much as anything else.....

**Comment by zanker** [comment]
😆

**Comment by ixti** [comment]
:+1:  from me :D

**Comment by mikegee** [comment]
🥔 ++

**Comment by tarcieri** [comment]
I'm just gonna go with the correct pronunciation being: "The HTTP Gem" 😜

**Comment by jkingdon** [comment]
Works for me. We'll still have this GitHub issue for the 🥔🥔🥔 lovers.

**Comment by jkingdon** [comment]
For posterity, the tweet in question (in case that URL goes bad at some point) is:

```
[@isntitvacant@hachyderm.io](https://twitter.com/isntitvacant)
[@isntitvacant](https://twitter.com/isntitvacant)
HTTP => hot potato
HTTPS => hot potatoes
HTTP2 => hot potato two, electric boogaloo
FTP => fast potato
SFTP => surprise, fast potato
```

**Pull request closed without merging**
