### PR TITLE
add socket_factory option

### PR DESCRIPTION
**Pull request by nerdrew**
Add an option for custom socket creation, e.g.

```
HTTP::Client.new(socket_factory: lambda { |host, port|
  sock = TCPSocket.open(host, port)
  sock.setsockopt(Socket::Option.int(:INET, Socket::IPPROTO_TCP, Socket::TCP_NODELAY, 1))
  sock
})
```

### CODE REVIEW

**Comment by tarcieri** [comment]
Rubocop isn't happy :(

This seems ok, although it might be nice to have a separate API specifically for disabling Nagle, and one that uses `HTTP::Options`, e.g.

`HTTP.nodelay(true)...`

or

`HTTP.socketopts(nodelay: true)...`

**Comment by ixti** [comment]
:+1: from me for API. But I see it a bit different:

``` ruby
def nodelay
  socket_options :delay => false
end

def socket_options(options)
  # ...
end
```

**Comment by ixti** [comment]
In fact I think we should have only `socket_options()` API (no sugar).

**Comment by tarcieri** [comment]
@ixti so I was talking to @nerdrew about that, and asking what other socket options we'd actually like to support, and the answer is really: none.

I have a new API suggestion:

```
HTTP.nodelay
```

Done!

**Comment by zanker** [comment]
My name is Zach Anker, and I approve of Tony's message.

**Comment by zanker** [comment]
My name is Zach Anker, and I approve of Tony's message.

**Comment by ixti** [comment]
@tarcieri if there's no other socket options we would like to support, then `nodelay` works for me as well! :D

**Comment by nerdrew** [comment]
Ok, alternative `nodelay` PR: https://github.com/httprb/http/pull/275/files

**Pull request closed without merging**
