### PR TITLE
rspec raise_error wants to know which type of error it is expecting.

### PR DESCRIPTION
**Pull request by kwando**
Also added a HTTP::UnexpectedError which can be used to indicate that something went wrong.

### CODE REVIEW

**Comment by tarcieri** [comment]
Can't say I'm really wild about the name `UnexpectedError`

**Comment by kwando** [comment]
Do you have a better name? ImplementationError?

**Comment by tarcieri** [comment]
I think I'd rather have meaningful exceptions

**Comment by kwando** [comment]
DoesNotRespondToToIntError? Anyway, I do not feel very strongly about this. It was just a way for me to make rspec stop complaining.

**Comment by kwando** [comment]
AFAIK that error would only be occur if there is a bug in HTTP.

**Comment by ixti** [comment]
This can be done a bit different way. Thanks for bringing this on. I'll take a look.

**Pull request closed without merging**
