### PR TITLE
Let the instrumenter log exceptions too

### PR DESCRIPTION
**Pull request by foca**
This seems like a missing piece in the instrumentation feature.

### CODE REVIEW

**Review by tarcieri — APPROVED** [review]
Looks good, thanks!

**Review by ixti — APPROVED** [review]
LGTM! Thank you!

**Comment by foca** [comment]
Is there any plan on releasing a new version soon? I'd like to have this on the gem at some point, instead of having to bundle the git fork, which is slower 😅

**Comment by tarcieri** [comment]
@foca https://rubygems.org/gems/http/versions/5.2.0

**Comment by foca** [comment]
You're the best! ❤️

**Pull request merged**
