### PR TITLE
adding 418 status code

### PR DESCRIPTION
**Pull request by mdayaram**

### CODE REVIEW

**Comment by ixti** [comment]
Reasons Hash is auto-generated (which is clearly stated in the head of the file: https://github.com/httprb/http/blob/master/lib/http/response/status/reasons.rb#L2) from: http://www.iana.org/assignments/http-status-codes/http-status-codes.xml

**Comment by ixti** [comment]
I plan to refactor `Status` class in general, so that it will allow you to add extra reasons.

**Comment by ixti** [comment]
Closing this in favor of #350

**Comment by mdayaram** [comment]
woops, missed that, sorry.

**Pull request closed without merging**
