### PR TITLE
Simplify test for sending large request bodies

### PR DESCRIPTION
**Pull request by janko-m**
The tests for large request bodies (which cover [this logic](https://github.com/httprb/http/blob/d7aa074d44c936bb1d82c72a87c4d538c31c56c4/lib/http/request/writer.rb#L98-L102)) in my opinion produces too many unnecessary specs.

<details>
<summary>Specs</summary>

```
    with a large request body
      with `.timeout(:null)`
        with a 68000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 68000 body and 702 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16000 body and 263 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 68000 body and 4 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 17000 body and 46 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16000 body and 67 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 17000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 17000 body and 496 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16500 body and 34 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 34000 body and 41 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 34000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 34000 body and 728 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16500 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16500 body and 900 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
      with `.timeout(6)`
        with a 68000 body and 792 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 17000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16000 body and 64 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 34000 body and 45 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 17000 body and 28 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 17000 body and 252 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 68000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 34000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16500 body and 31 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16000 body and 739 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 68000 body and 9 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16500 body and 456 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16500 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 34000 body and 420 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
      with `.timeout({:read=>2, :write=>2, :connect=>2})`
        with a 17000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16500 body and 353 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 34000 body and 614 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 17000 body and 40 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 68000 body and 609 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16000 body and 49 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 34000 body and 3 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 34000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 68000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16500 body and 91 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 68000 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16000 body and 780 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 17000 body and 577 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
        with a 16500 body and 0 of fuzzing
          returns a large body
          when bytesize != length
            returns a large body
```
</details><br>

So I narrowed it down to three specs, one for each type of timeout, using a sufficiently large response body. I tested that the tests fail if I

* remove the `until data.empty?` loop
* replace `bytesize` with `size`
* replace `byteslice` with `slice`

so we should still have the same coverage.

### CODE REVIEW

**Comment by ixti** [comment]
I think the idea behind this tests were to add some fuzzy testing. I don't have strong opinion about this particular test though.

@zanker I think you know this part better, any thoughts?

/cc @httprb/core

**Comment by janko-m** [comment]
> I'd consider keeping a 16k one + a larger one to have a bit of variance for buffer sizes.

On my machine (2012 MacBook Pro) a 16KB body wasn't large enough to hit the TCP buffer limit, the limit for seems to be 255KB. So I was wondering whether it's worthwhile to keep the 16KB request body test, as it probably wouldn't be testing anything more than what a 3-byte request body isn't already testing.

**Comment by zanker** [comment]
Interesting, I didn't realize the TCP buffer limit was that high on a MacBook. Seems reasonable ot me then!

**Comment by ixti** [comment]
Thanks!

**Pull request merged**
