### PR TITLE
Add .retriable feature to Http - Rebased

### PR DESCRIPTION
**Pull request by tomprats**
Rebase of https://github.com/httprb/http/pull/598 with:
- hashrockets removed
- rubocop formatting updates
- creating a response with uri option

I don't understand the internals super well, but the changes I made off of the original were minor enough to not really change any actual functionality. Tests and cops all pass!

### CODE REVIEW

**Comment by tomprats** [comment]
I had some time, so I ended up rebasing and fixing the lint and test errors.

@ixti would you mind taking a look again?

**Comment by ixti** [comment]
That looks amazing! Thank you! Will take me some time reviewing though... :D

**Comment by tomprats** [comment]
@ixti Any luck?

**Comment by tomprats** [comment]
I've been using this in prod for a few months now and so far haven't noticed any issues :)

**Review by tarcieri — APPROVED** [review]

**Comment by tarcieri** [comment]
Thanks!

**Comment by ixti** [comment]
@mylesboone Will cut the release this week.

**Comment by mylesboone** [comment]
@ixti any chance we could get the release this week? it would be a massive help!

**Comment by cspeer** [comment]
I'd also like to see this released as a new gem version. Thanks @ixti

**Pull request merged**
